shinyUI(fluidPage(

  headerPanel('Supplementary material: Guidance framework for the selection and evaluation of indicators for an Ecosystem Approach to Fisheries Management (EAFM) '),
  
  
  sidebarPanel(width = 2,
      #downloadButton('downloadPlot', 'Download Plot'),
       sliderInput('range', 'Range', 
                   min = 1970,
                   max = 2015, 
                   value = c(1970, 2015)
                   ),
    
      checkboxGroupInput('var', 'Variable',
                         choices = c(
                                     #'Biomass',
                                     'Biomass_s',
                                     #'BiomassClupeids',
                                     'BiomassClupeids_s',
                                     #'BiomassFinfish',
                                     'BiomassFinfish_s',
                                     #'BiomassFlatfish',
                                     'BiomassFlatfish_s',
                                    # 'BiomassForage',
                                     'BiomassForage_s',
                                     #'BiomassGadoids',
                                     'BiomassGadoids_s',
                                     #'BiomassGroundfish',
                                     'BiomassGroundfish_s',
                                     #'BiomassSkates',
                                     'BiomassSkates_s',
                                     #'BiomassTL2',
                                     'BiomassTL2_s',
                                     #'BiomassTL3',
                                     'BiomassTL3_s',
                                     #'BiomassTL4',
                                     'BiomassTL4_s',
                                     #'BPelagicToDemersal',
                                     'BPelagicToDemersal_s',
                                     #'BTGLargeBenthivore',
                                     'BTGLargeBenthivore_s',
                                     #'BTGMediumBenthivore',
                                     'BTGMediumBenthivore_s',
                                     #'BTGPiscivore',
                                     'BTGPiscivore_s',
                                     #'BTGPlanktivore',
                                     'BTGPlanktivore_s',
                                    # 'BTGZoopiscivore',
                                     'BTGZoopiscivore_s',
                                     #'CCLargeBenthivore',
                                     'CCLargeBenthivore_s',
                                     #'CCMediumBenthivore',
                                     'CCMediumBenthivore_s',
                                     #'CCPiscivore',
                                     'CCPiscivore_s',
                                     #'CCPlanktivore',
                                     'CCPlanktivore_s',
                                     #'CCZoopiscivore',
                                     'CCZoopiscivore_s',
                                     #'CommunityCondition',
                                     'CommunityCondition_s',
                                     #'DiversityTargetSpp.L',
                                     'DiversityTargetSpp.L_s',
                                     #'FishinginBalance.L',
                                     'FishinginBalance.L_s',
                                     #'FishingPressure.L',
                                     'FishingPressure.L_s',
                                     #'FPClupeids.L',
                                     'FPClupeids.L_s',
                                     #'FPFinfish.L',
                                     'FPFinfish.L_s',
                                     #'FPFlatfish.L',
                                     'FPFlatfish.L_s',
                                     #'FPForageFish.L',
                                     'FPForageFish.L_s',
                                     #'FPGadoids.L',
                                     'FPGadoids.L_s',
                                     #'FPGroundfish.L',
                                     'FPGroundfish.L_s',
                                     #'FPSkates.L',
                                     'FPSkates.L_s',
                                     #'Heips',
                                     'Heips_s',
                                    # 'HillN1Diversity',
                                     'HillN1Diversity_s',
                                     #'HillN2Dominance',
                                     'HillN2Dominance_s',
                                    # 'Intrinsicvulnerabilityindex.L',
                                     'Intrinsicvulnerabilityindex.L_s',
                                     #'InverseCVBiomass',
                                     'InverseCVBiomass_s',
                                     #'KemptonQ',
                                     'KemptonQ_s',
                                     #'Landings.L',
                                     'Landings.L_s',
                                     #'LargeFishIndicator',
                                     'LargeFishIndicator_s',
                                     #'LargeSpeciesIndicator',
                                     'LargeSpeciesIndicator_s',
                                    #'LClupeids.L',
                                     'LClupeids.L_s',
                                     #'LFinfish.L',
                                     'LFinfish.L_s',
                                     #'LFlatfish.L',
                                     'LFlatfish.L_s',
                                    # 'LForageFish.L',
                                     'LForageFish.L_s',
                                     #'LGadoids.L',
                                     'LGadoids.L_s',
                                     #'LGroundfish.L',
                                     'LGroundfish.L_s',
                                     #'LInvertebrates.L',
                                     'LInvertebrates.L_s',
                                     #'LLargePelagic.L',
                                     'LLargePelagic.L_s',
                                     #'LSkates.L',
                                     'LSkates.L_s',
                                     #'MargalefGroundfish',
                                     'MargalefGroundfish_s',
                                     #'MargalefRichness',
                                     'MargalefRichness_s',
                                     #'MarineTrophicIndex.L',
                                     'MarineTrophicIndex.L_s',
                                     #'MeanLengthAbundance',
                                     'MeanLengthAbundance_s',
                                     #'MeanLengthBiomass',
                                     'MeanLengthBiomass_s',
                                     #'MeanLifespan',
                                     'MeanLifespan_s',
                                     #'MeanTrophicLevel',
                                     'MeanTrophicLevel_s',
                                     #'MeanTrophicLevel.L',
                                     'MeanTrophicLevel.L_s',
                                     #'PielouEvenness',
                                     'PielouEvenness_s',
                                     #'PropPredatoryFish',
                                     'PropPredatoryFish_s',
                                     #'ShannonDiversity',
                                     'ShannonDiversity_s',
                                     #'SpeciesRichness',
                                     'SpeciesRichness_s',
                                     #'MMLengthBiomass',
                                     'MMLengthBiomass_s',
                                    # 'MMLengthAbundance', 
                                     'MMLengthAbundance_s'),
                                      selected = c('Biomass_s',
                                                   'BiomassClupeids_s',
                                                   'BiomassFinfish_s',
                                                   'BiomassForage_s',
                                                   'BiomassTL3_s',
                                                   'BPelagicToDemersal_s',
                                                   'BTGPlanktivore_s'))
                                      ),
  
  
  mainPanel(
    plotOutput('plot1',width = "120%"),
    plotOutput('plot2',width = "120%"),
    plotOutput('plot3', width = "125%", height = "3400px")
  )

  
  
)) # end parenthesis - do not delete